# general settings
name: motion_mag_test # XXNet_convgru_deblurvoxel #XXNet 
model_type: EventBasedMotionMagModel
scale: 1
num_gpu: 1 # 4
manual_seed: 10

datasets:
  train:
    type: EventMagRecurrentDataset
    dataroot: /mnt/workspace/chenyutian/project/EMM/datasets/trainset_tiny

    # interpolation settings
    num_end_interpolation: 1 
    num_inter_interpolation: 29
    # voxel settings
    norm_voxel: true
    one_voxel_flag: true
    return_deblur_voxel: false

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # augment
    gt_size: 256
    use_hflip: true
    use_rot: true
    random_reverse: false
    # data loader settings
    use_shuffle: true
    num_worker_per_gpu: 6 #6
    batch_size_per_gpu: 1 
    dataset_enlarge_ratio: 8  
    prefetch_mode: cpu  # ?
    num_prefetch_queue: 2

  val:
    # name: gopro-twoblur-test
    type: EventMagRecurrentDataset

    dataroot: /mnt/workspace/chenyutian/project/EMM/datasets/trainset_tiny

    # interpolation settings
    num_end_interpolation: 1 # m
    num_inter_interpolation: 29 # n
    # voxel settings
    norm_voxel: true
    one_voxel_flag: true
    return_deblur_voxel: false

    io_backend:
      type: disk

    gt_size: ~
    use_hflip: false
    use_rot: false

dataset_name: UND




# network structures
network_g:
  type: EvsMotionMagNet
  img_chn: 3 # 6 for two image, 26 for image and voxel
  ev_chn: 2
  num_encoders: 2
  base_num_channels: 32
  # recurrent_block_type: 'simpleconvThendown' # 'convlstm' or 'convgru' or 'simpleconv' or 'simpleconvThendown'
  num_block: 1  # num_block of blocks in each encoder
  num_residual_blocks: 2 # num_block of resblock in the bottleneck of unet


# path
path:
  # pretrain_network_g: experiments/Finetune_Sharpinterpo_Final_15skip/models/net_g_6000.pth
  strict_load_g: true
  resume_state: ~ 
  training_states: ~ # save current trainig model states, for resume
  root: /mnt/data/sail_3090/chenyutian/project/REFID  # set this option ONLY in TEST!!!

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 10000 
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1
    reduction: mean
    
  regular_opt:
    type: CharbonnierLoss
    loss_weight: 0.01
    reduction: mean

# validation settings
val:
  val_freq: !!float 6000 # 2e4
  save_img: true  
  save_gt: false
  grids: ~  
  crop_size: ~
  max_minibatch: 8

  metrics_interpo:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false 

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2000
  use_tb_logger: true
  # wandb:
  #   project: your_project_name
  #   resume_id: x

# dist training settings
dist_params:
  backend: nccl
  port: 29500

